[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
# TODO Updating aiobotocore causes tests to fail, investigate
aiobotocore = "==2.18.0"
aiohttp = "==3.11.11"
bidict = "==0.23.1"
cacheout = "==0.16.0"
docker-image-py = "==0.1.13"
fastapi = {extras = ["standard"], version = "==0.115.6"}
jinja-cli = "==1.2.2"
marisa-trie = "==1.2.1"
motor = "==3.6.0"
requests = "==2.32.3"
sfapi-client = "==0.3.2"
uvicorn = {version = "==0.34.0", extras = ["standard"]}

[dev-packages]
coverage = "==7.6.10"
ipython = "==8.31.0"
pytest = "==8.3.4"
pytest-asyncio = "==0.25.2"
pytest-cov = "==6.0.0"

[requires]
python_version = "3.11"
